name: Bug Report
description: File a bug report
title: ""
labels: ["bug"]
assignees:
  - timheuer
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: vsversion
    attributes:
      label: Visual Studio Version
      description: Copy the Visual Studio version from your Help...About Visual Studio menu
      placeholder: Version 17.8.5
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. From the Output window for "GitHub Actions for VS"
