name: "Base build"

on: workflow_call
      
jobs:
  build:
    outputs:
      version: ${{ steps.vsix_version.outputs.version-number }}
    name: Build 
    runs-on: windows-2022
    env:
        PROJECT_PATH: "src/GitHubActionsVS.sln"
      
    steps:
    - uses: actions/checkout@v3

    - name: 🧰 Setup .NET build dependencies
      uses: timheuer/bootstrap-dotnet@v1
      with:
        nuget: 'false'
        sdk: 'false'
        msbuild: 'true'

    - name: 🏗️ Build
      run: msbuild ${{ env.PROJECT_PATH }} /p:Configuration=Release /v:m -restore /p:OutDir=\_built

    - name: ⬆️ Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}.vsix
        path: /_built/**/*.vsix