name: "Publish"

on:
  workflow_dispatch:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
      
jobs:
  build:
    name: Build and Test
    uses: ./.github/workflows/_build.yaml

  publish:
    needs: build
    name: Publish
    runs-on: windows-2022
    env:
        VERSION: ${{ needs.build.outputs.version }}

    steps:
    - name: Version from build
      run: echo ${{ env.VERSION }}

    - name: Download Package artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ github.event.repository.name }}.vsix
    
    - name: Upload to VsixGallery
      uses: timheuer/openvsixpublish@v1
      with:
        vsix-file: ${{ github.event.repository.name }}.vsix

    - name: Tag and Release
      id: tag_release
      uses: softprops/action-gh-release@v1
      with:
        body: Release ${{ needs.build.outputs.version }}
        tag_name: ${{ env.VERSION }}
        generate_release_notes: true
        files: |
          **/*.vsix

    - name: Publish extension to Marketplace
      #if: ${{ contains(github.event.head_commit.message, '[release]') }}
      uses: cezarypiatek/VsixPublisherAction@0.1
      with:
        extension-file: '${{ github.event.repository.name }}.vsix'
        publish-manifest-file: 'vs-publish.json'
        personal-access-code: ${{ secrets.VS_PUBLISHER_ACCESS_TOKEN }}
    